<a href="https://colab.research.google.com/github/Prashantkumartalan43/EDA/blob/main/superstore_sales_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("SuperStoreOrders.csv")

df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2.0,0.0,106.140,35.46,Medium,2011.0
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3.0,0.1,36.036,9.72,Medium,2011.0
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4.0,0.0,29.640,8.17,High,2011.0
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3.0,0.5,-26.055,4.82,High,2011.0
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5.0,0.1,37.770,4.70,Medium,2011.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14954 entries, 0 to 14953
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        14954 non-null  object
 1   order_date      14954 non-null  object
 2   ship_date       14954 non-null  object
 3   ship_mode       14954 non-null  object
 4   customer_name   14954 non-null  object
 5   segment         14954 non-null  object
 6   state           14954 non-null  object
 7   country         14954 non-null  object
 8   market          14954 non-null  object
 9   region          14954 non-null  object
 10  product_id      14954 non-null  object
 11  category        14954 non-null  object
 12  sub_category    14954 non-null  object
 13  product_name    14953 non-null  object
 14  sales           14953 non-null  object
 15  quantity        14953 non-null  float64
 16  discount        14953 non-null  float64
 17  profit          14953 non-null  float64
 18  shipping_cost   14953 non-null  float64
 19  order_priority  14953 non-null  object
 20  year            14953 non-null  float64
dtypes: float64(5), object(16)
memory usage: 2.4+ MB

In [5]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  14953.000000  14953.000000  14953.000000   14953.000000  14953.000000
mean       3.464589      0.145922     28.774218      26.871343   2011.398248
std        2.267396      0.215765    166.626470      59.812669      0.489553
min        1.000000      0.000000  -3701.892800       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.630000   2011.000000
50%        3.000000      0.000000      9.072000       7.850000   2011.000000
75%        5.000000      0.200000     36.660000      24.030000   2012.000000
max       14.000000      0.850000   4630.475500     933.570000   2012.000000

In [6]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      1
sales             1
quantity          1
discount          1
profit            1
shipping_cost     1
order_priority    1
year              1
dtype: int64

In [14]:
df.dropna(inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["order_date"] = pd.to_datetime(df["order_date"], format='mixed')
df["ship_date"] = pd.to_datetime(df["ship_date"], format='mixed')

In [16]:
df['sales'] = df['sales'].astype(str).str.replace(r'[$,\s]', '', regex=True)
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')

In [28]:
print("Total Sales:", df["sales"].sum())
print("Average Sales:", df["sales"].mean())

Total Sales: 3718229
Average Sales: 248.66107135691834